### ISSUE TITLE
Whitescreen after build

### ISSUE THREAD

**Issue by svrgnty** [xavierfiechter/specter-diy-app-dice-rolls#2]
When compiling specter DIY (v1.8.3) with the dice rolls app included, the build process gives no errors but when it's flashed to the discovery board, the screen is white. The firmware does not seem to load correctly. Below are the steps taken. Thanks for any help!

```
# clone repositories
git clone https://github.com/cryptoadvance/specter-diy.git --recursive
git clone https://github.com/xavierfiechter/specter-diy-app-dice-rolls.git

# add diceroll app
cp -R specter-diy-app-dice-rolls/dicerolls specter-diy/src/apps/dicerolls
echo '__all__.append("dicerolls")' >> specter-diy/src/apps/__init__.py

# compile specter https://github.com/cryptoadvance/specter-diy/blob/master/docs/reproducible-build.md 
cd specter-diy
cp bootloader/keys/production/pubkeys.c bootloader/keys/selfsigned/
docker build -t diy .
docker run -ti -v `pwd`:/app diy
```

**Comment by xavierfiechter** [comment]
@svrgnty it was build on an older version of Specter DIY. I will have to check what has changed.

**Comment by svrgnty** [comment]
Hi @xavierfiechter 
I figured out the issue and created a pull request
https://github.com/xavierfiechter/specter-diy-app-dice-rolls/pull/3

**Comment by xavierfiechter** [comment]
That's awesome. Thanks.
